(() => {
'use strict';
const reduce=matchMedia('(prefers-reduced-motion: reduce)'),scene=document.querySelector('.gaucho-scene'),canvas=document.createElement('canvas');canvas.className='cinema-atmosphere';canvas.setAttribute('aria-hidden','true');document.body.append(canvas);const ctx=canvas.getContext('2d');if(!ctx)return;
let w=0,h=0,time=0,last=0,frame=0,paused=false,targetX=0,targetY=0,x=0,y=0,flare=0,current=0,drift=0,lastTrail=0;const sparks=[];
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}
function allowed(){return !paused&&!reduce.matches&&!document.hidden}
function sync(){if(allowed()&&!frame){last=0;frame=requestAnimationFrame(draw)}else if(!allowed()){cancelAnimationFrame(frame);frame=0;sparks.length=0;ctx.clearRect(0,0,w,h)}}
function glow(cx,cy,r,alpha,color){const grad=ctx.createRadialGradient(cx,cy,0,cx,cy,r);grad.addColorStop(0,`rgba(${color},${alpha})`);grad.addColorStop(.3,`rgba(${color},${alpha*.25})`);grad.addColorStop(1,`rgba(${color},0)`);ctx.fillStyle=grad;ctx.fillRect(cx-r,cy-r,r*2,r*2)}
function emit(cx,cy,count,burst){if(!allowed()||document.querySelector('dialog[open]'))return;for(let i=0;i<count;i++){const angle=Math.random()*Math.PI*2,speed=(burst?35:8)+Math.random()*(burst?100:20);sparks.push({x:cx,y:cy,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-15,life:1.1+Math.random()*.6,max:1.7,r:.7+Math.random()*1.7})}if(sparks.length>150)sparks.splice(0,sparks.length-150)}
function draw(now){frame=0;if(!allowed())return;if(last&&now-last<32){frame=requestAnimationFrame(draw);return}const dt=last?Math.min((now-last)/1000,.06):.033;last=now;time+=dt;flare*=.95;drift*=.94;x+=(targetX-x)*.04;y+=(targetY-y)*.04;scene.style.setProperty('--camera-x',x+'px');scene.style.setProperty('--camera-y',y+'px');ctx.clearRect(0,0,w,h);
const mobile=w<=600,r=scene.getBoundingClientRect(),scale=Math.max(r.width/1672,r.height/940),iw=1672*scale,ih=940*scale,cx=r.left+(r.width-iw)*(mobile?.44:.5)+iw*.48,cy=r.top+(r.height-ih)*(mobile?.15:.5)+ih*.384;
if(current===0){ctx.save();ctx.lineCap='round';for(let strand=0;strand<3;strand++){const height=mobile?92:135;for(let j=0;j<20;j++){const p=j/20,q=(j+1)/20;const sway=t=>Math.sin(t*9-time*.65+strand*1.8)*t*12+Math.sin(t*16-time*.4)*t*4;ctx.beginPath();ctx.moveTo(cx+sway(p)+strand*2,cy-p*height);ctx.lineTo(cx+sway(q)+strand*2,cy-q*height);ctx.lineWidth=1.2+p*3;ctx.strokeStyle=`rgba(225,223,214,${Math.sin(p*Math.PI)*.045*(.65+.35*Math.sin(time*.7+strand))})`;ctx.shadowColor='rgba(220,218,208,.09)';ctx.shadowBlur=5;ctx.stroke();}}ctx.restore();}
for(let i=0;i<(mobile?38:68);i++){const seed=(i*0.61803398875)%1,speed=18+(i%7)*5,life=((time*speed+i*51)%(h*.88))/(h*.88),px=((seed*w+Math.sin(time*.7+i)*16+Math.sin(life*11+i)*25+drift*18)%w+w)%w,py=h+12-life*h*.88,alpha=Math.sin(life*Math.PI)*(.22+(i%4)*.11)*(current?.65:1),size=.65+(i%4)*.35;ctx.strokeStyle=`rgba(255,${Math.round(160-life*85)},35,${alpha})`;ctx.lineWidth=size;ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px-Math.sin(time+i)*1.5,py+2+size*2);ctx.stroke();if(i%3===0)glow(px,py,5,alpha*.22,'255,96,18');}
ctx.globalCompositeOperation='screen';const lx=w*.76+x*2+Math.sin(time*.12)*14,ly=h*.2+y*2,strength=.08+flare*.13;glow(lx,ly,mobile?90:160,strength,'255,181,83');for(let i=1;i<4;i++)glow(lx+(w*.38-lx)*i*.45,ly+(h*.68-ly)*i*.45,12+i*11,strength*.3,i%2?'245,191,117':'128,171,160');
for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;if(p.life<=0){sparks.splice(i,1);continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy-=24*dt;p.vx*=.985;ctx.fillStyle=`rgba(255,145,43,${Math.min(.75,p.life/p.max)})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();if(p.r>1.7)glow(p.x,p.y,6,p.life*.1,'255,92,20')}
ctx.globalCompositeOperation='source-over';frame=requestAnimationFrame(draw)}
addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){targetX=(e.clientX/w-.5)*9;targetY=(e.clientY/h-.5)*7;}if(performance.now()-lastTrail>35){emit(e.clientX,e.clientY,2,false);lastTrail=performance.now();}},{passive:true});addEventListener('pointerdown',e=>{emit(e.clientX,e.clientY,w<601?18:30,true);flare=Math.max(flare,.3)},{passive:true});document.addEventListener('scenechange',e=>{current=e.detail.index;drift=e.detail.direction;flare=1;targetY=current? -2:0;});
current=Math.max(0,[...document.querySelectorAll('.scene-panel')].findIndex(p=>p.classList.contains('is-active')));
document.querySelector('#effects-toggle').addEventListener('click',e=>{paused=!paused;document.body.classList.toggle('effects-paused',paused);e.currentTarget.textContent=paused?'▶ Ativar efeitos':'Ⅱ Pausar efeitos';e.currentTarget.setAttribute('aria-pressed',String(paused));sync()});addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',sync);reduce.addEventListener('change',sync);resize();sync();
})();
